Share Link
Use this to link directly to your timeline.
https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1LRWBRggpXWtiBNXl9xoTx8ockmriQM2o&font=Default&lang=en&initial_zoom=2&height=650
If you're embedding on Medium.com or other oembed-aware services, just paste this link on a line by itself where you want your timeline to appear.

Embed
Copy this embed code and paste it on your site where you want your timeline to appear (just like a YouTube video).
<iframe src='https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1LRWBRggpXWtiBNXl9xoTx8ockmriQM2o&font=Default&lang=en&initial_zoom=2&height=650' width='100%' height='650' webkitallowfullscreen mozallowfullscreen allowfullscreen frameborder='0'></iframe>
